import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      colors: {
        "node-navigate": "hsl(var(--node-navigate))",
        "node-foreach": "hsl(var(--node-foreach))",
        "node-while": "hsl(var(--node-while))",
        "node-for": "hsl(var(--node-for))",
        "node-click": "hsl(var(--node-click))",
        "node-check_existence": "hsl(var(--node-check_existence))",
        "node-default": "hsl(var(--node-default))",
        "node-type": "hsl(var(--node-type))",
        "node-wait": "hsl(var(--node-wait))",
        "node-screenshot": "hsl(var(--node-screenshot))",
        "node-scroll": "hsl(var(--node-scroll))",
        "node-locator": "hsl(var(--node-locator))",
        "node-count": "hsl(var(--node-count))",
        "node-all": "hsl(var(--node-all))",
        "node-first": "hsl(var(--node-first))",
        "node-last": "hsl(var(--node-last))",
        "node-nth": "hsl(var(--node-nth))",
        "node-map": "hsl(var(--node-map))",
        "node-textContent": "hsl(var(--node-textContent))",
        "node-innerText": "hsl(var(--node-innerText))",
        "node-inputValue": "hsl(var(--node-inputValue))",
        "node-getAttribute": "hsl(var(--node-getAttribute))",
        "node-isVisible": "hsl(var(--node-isVisible))",
        "node-isEnabled": "hsl(var(--node-isEnabled))",
        "node-isChecked": "hsl(var(--node-isChecked))",
        "node-hover": "hsl(var(--node-hover))",
        "node-check": "hsl(var(--node-check))",
        "node-uncheck": "hsl(var(--node-uncheck))",
        "node-cookie": "hsl(var(--node-cookie))",
        "node-localstorage": "hsl(var(--node-localstorage))",
        "node-if": "hsl(var(--node-if))",
        "node-extract": "hsl(var(--node-extract))",
        "node-break": "hsl(var(--node-break))",
        "node-continue": "hsl(var(--node-continue))",
        "node-stop": "hsl(var(--node-stop))",
        "node-set": "hsl(var(--node-set))",
        "node-document": "hsl(var(--node-document))",
        "node-title": "hsl(var(--node-title))",
        "node-url": "hsl(var(--node-url))",
        "node-content": "hsl(var(--node-content))",
        "node-viewport": "hsl(var(--node-viewport))",
        "node-press": "hsl(var(--node-press))",
        "node-selectOption": "hsl(var(--node-selectOption))",
        "node-waitFor": "hsl(var(--node-waitFor))",
        "node-waitForURL": "hsl(var(--node-waitForURL))",
        "node-waitForLoadState": "hsl(var(--node-waitForLoadState))",
        "node-httpRequest": "hsl(var(--node-httpRequest))",
        "node-file": "hsl(var(--node-file))",
        "node-mouse": "hsl(var(--node-mouse))",
        "node-ocrCaptcha": "hsl(var(--node-ocrCaptcha))",
        "node-imageDetection": "hsl(var(--node-imageDetection))",
        "node-imageMatch": "hsl(var(--node-imageMatch))",
        "node-sliderCaptcha": "hsl(var(--node-sliderCaptcha))",
        "node-script": "hsl(var(--node-script))",
        "node-newPage": "hsl(var(--node-newPage))",
        "node-switchPage": "hsl(var(--node-switchPage))",
        "node-closePage": "hsl(var(--node-closePage))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
