// 默认节点颜色样式
const DEFAULT_BORDER = "border-node-default shadow-[0_0_15px_-3px_hsl(var(--node-default)/0.4)]";
const DEFAULT_ICON_BG = "bg-node-default/15 text-node-default";

export const colorMap: Record<string, string> = {
  navigate: "border-node-navigate shadow-[0_0_15px_-3px_hsl(var(--node-navigate)/0.4)]",
  click: "border-node-click shadow-[0_0_15px_-3px_hsl(var(--node-click)/0.4)]",
  check_existence: "border-node-check_existence shadow-[0_0_15px_-3px_hsl(var(--node-check_existence)/0.4)]",
  type: "border-node-type shadow-[0_0_15px_-3px_hsl(var(--node-type)/0.4)]",
  wait: "border-node-wait shadow-[0_0_15px_-3px_hsl(var(--node-wait)/0.4)]",
  screenshot: "border-node-screenshot shadow-[0_0_15px_-3px_hsl(var(--node-screenshot)/0.4)]",
  scroll: "border-node-scroll shadow-[0_0_15px_-3px_hsl(var(--node-scroll)/0.4)]",
  foreach: "border-node-foreach shadow-[0_0_15px_-3px_hsl(var(--node-foreach)/0.4)]",
  while: "border-node-while shadow-[0_0_15px_-3px_hsl(var(--node-while)/0.4)]",
  for: "border-node-for shadow-[0_0_15px_-3px_hsl(var(--node-for)/0.4)]",
  locator: "border-node-locator shadow-[0_0_15px_-3px_hsl(var(--node-locator)/0.4)]",
  count: "border-node-count shadow-[0_0_15px_-3px_hsl(var(--node-count)/0.4)]",
  all: "border-node-all shadow-[0_0_15px_-3px_hsl(var(--node-all)/0.4)]",
  first: "border-node-first shadow-[0_0_15px_-3px_hsl(var(--node-first)/0.4)]",
  last: "border-node-last shadow-[0_0_15px_-3px_hsl(var(--node-last)/0.4)]",
  nth: "border-node-nth shadow-[0_0_15px_-3px_hsl(var(--node-nth)/0.4)]",
  map: "border-node-map shadow-[0_0_15px_-3px_hsl(var(--node-map)/0.4)]",
  textContent: "border-node-textContent shadow-[0_0_15px_-3px_hsl(var(--node-textContent)/0.4)]",
  innerText: "border-node-innerText shadow-[0_0_15px_-3px_hsl(var(--node-innerText)/0.4)]",
  inputValue: "border-node-inputValue shadow-[0_0_15px_-3px_hsl(var(--node-inputValue)/0.4)]",
  getAttribute: "border-node-getAttribute shadow-[0_0_15px_-3px_hsl(var(--node-getAttribute)/0.4)]",
  isVisible: "border-node-isVisible shadow-[0_0_15px_-3px_hsl(var(--node-isVisible)/0.4)]",
  isEnabled: "border-node-isEnabled shadow-[0_0_15px_-3px_hsl(var(--node-isEnabled)/0.4)]",
  isChecked: "border-node-isChecked shadow-[0_0_15px_-3px_hsl(var(--node-isChecked)/0.4)]",
  hover: "border-node-hover shadow-[0_0_15px_-3px_hsl(var(--node-hover)/0.4)]",
  check: "border-node-check shadow-[0_0_15px_-3px_hsl(var(--node-check)/0.4)]",
  uncheck: "border-node-uncheck shadow-[0_0_15px_-3px_hsl(var(--node-uncheck)/0.4)]",
  cookie: "border-node-cookie shadow-[0_0_15px_-3px_hsl(var(--node-cookie)/0.4)]",
  localstorage: "border-node-localstorage shadow-[0_0_15px_-3px_hsl(var(--node-localstorage)/0.4)]",
  if: "border-node-if shadow-[0_0_15px_-3px_hsl(var(--node-if)/0.4)]",
  extract: "border-node-extract shadow-[0_0_15px_-3px_hsl(var(--node-extract)/0.4)]",
  break: "border-node-break shadow-[0_0_15px_-3px_hsl(var(--node-break)/0.4)]",
  continue: "border-node-continue shadow-[0_0_15px_-3px_hsl(var(--node-continue)/0.4)]",
  stop: "border-node-stop shadow-[0_0_15px_-3px_hsl(var(--node-stop)/0.4)]",
  set: "border-node-set shadow-[0_0_15px_-3px_hsl(var(--node-set)/0.4)]",
  document: "border-node-document shadow-[0_0_15px_-3px_hsl(var(--node-document)/0.4)]",
  title: "border-node-title shadow-[0_0_15px_-3px_hsl(var(--node-title)/0.4)]",
  url: "border-node-url shadow-[0_0_15px_-3px_hsl(var(--node-url)/0.4)]",
  content: "border-node-content shadow-[0_0_15px_-3px_hsl(var(--node-content)/0.4)]",
  viewport: "border-node-viewport shadow-[0_0_15px_-3px_hsl(var(--node-viewport)/0.4)]",
  press: "border-node-press shadow-[0_0_15px_-3px_hsl(var(--node-press)/0.4)]",
  selectOption: "border-node-selectOption shadow-[0_0_15px_-3px_hsl(var(--node-selectOption)/0.4)]",
  waitFor: "border-node-waitFor shadow-[0_0_15px_-3px_hsl(var(--node-waitFor)/0.4)]",
  waitForURL: "border-node-waitForURL shadow-[0_0_15px_-3px_hsl(var(--node-waitForURL)/0.4)]",
  waitForLoadState: "border-node-waitForLoadState shadow-[0_0_15px_-3px_hsl(var(--node-waitForLoadState)/0.4)]",
  httpRequest: "border-node-httpRequest shadow-[0_0_15px_-3px_hsl(var(--node-httpRequest)/0.4)]",
  file: "border-node-file shadow-[0_0_15px_-3px_hsl(var(--node-file)/0.4)]",
  mouse: "border-node-mouse shadow-[0_0_15px_-3px_hsl(var(--node-mouse)/0.4)]",
  ocrCaptcha: "border-node-ocrCaptcha shadow-[0_0_15px_-3px_hsl(var(--node-ocrCaptcha)/0.4)]",
  sliderCaptcha: "border-node-sliderCaptcha shadow-[0_0_15px_-3px_hsl(var(--node-sliderCaptcha)/0.4)]",
  script: "border-node-script shadow-[0_0_15px_-3px_hsl(var(--node-script)/0.4)]",
  newPage: "border-node-newPage shadow-[0_0_15px_-3px_hsl(var(--node-newPage)/0.4)]",
  switchPage: "border-node-switchPage shadow-[0_0_15px_-3px_hsl(var(--node-switchPage)/0.4)]",
  closePage: "border-node-closePage shadow-[0_0_15px_-3px_hsl(var(--node-closePage)/0.4)]",
};

export const iconBgMap: Record<string, string> = {
  navigate: "bg-node-navigate/15 text-node-navigate",
  foreach: "bg-node-foreach/15 text-node-foreach",
  while: "bg-node-while/15 text-node-while",
  for: "bg-node-for/15 text-node-for",
  click: "bg-node-click/15 text-node-click",
  check_existence: "bg-node-check_existence/15 text-node-check_existence",
  type: "bg-node-type/15 text-node-type",
  wait: "bg-node-wait/15 text-node-wait",
  screenshot: "bg-node-screenshot/15 text-node-screenshot",
  scroll: "bg-node-scroll/15 text-node-scroll",
  locator: "bg-node-locator/15 text-node-locator",
  count: "bg-node-count/15 text-node-count",
  all: "bg-node-all/15 text-node-all",
  first: "bg-node-first/15 text-node-first",
  last: "bg-node-last/15 text-node-last",
  nth: "bg-node-nth/15 text-node-nth",
  map: "bg-node-map/15 text-node-map",

  textContent: "bg-node-textContent/15 text-node-textContent",
  innerText: "bg-node-innerText/15 text-node-innerText",
  inputValue: "bg-node-inputValue/15 text-node-inputValue",
  getAttribute: "bg-node-getAttribute/15 text-node-getAttribute",

  isVisible: "bg-node-isVisible/15 text-node-isVisible",
  isEnabled: "bg-node-isEnabled/15 text-node-isEnabled",
  isChecked: "bg-node-isChecked/15 text-node-isChecked",

  hover: "bg-node-hover/15 text-node-hover",
  check: "bg-node-check/15 text-node-check",
  uncheck: "bg-node-uncheck/15 text-node-uncheck",

  cookie: "bg-node-cookie/15 text-node-cookie",
  localstorage: "bg-node-localstorage/15 text-node-localstorage",

  if: "bg-node-if/15 text-node-if",
  extract: "bg-node-extract/15 text-node-extract",
  break: "bg-node-break/15 text-node-break",
  continue: "bg-node-continue/15 text-node-continue",
  stop: "bg-node-stop/15 text-node-stop",

  set: "bg-node-set/15 text-node-set",
  document: "bg-node-document/15 text-node-document",
  title: "bg-node-title/15 text-node-title",
  url: "bg-node-url/15 text-node-url",
  content: "bg-node-content/15 text-node-content",
  viewport: "bg-node-viewport/15 text-node-viewport",

  press: "bg-node-press/15 text-node-press",
  selectOption: "bg-node-selectOption/15 text-node-selectOption",
  waitFor: "bg-node-waitFor/15 text-node-waitFor",
  waitForURL: "bg-node-waitForURL/15 text-node-waitForURL",
  waitForLoadState: "bg-node-waitForLoadState/15 text-node-waitForLoadState",
  httpRequest: "bg-node-httpRequest/15 text-node-httpRequest",
  file: "bg-node-file/15 text-node-file",
  mouse: "bg-node-mouse/15 text-node-mouse",
  ocrCaptcha: "bg-node-ocrCaptcha/15 text-node-ocrCaptcha",
  sliderCaptcha: "bg-node-sliderCaptcha/15 text-node-sliderCaptcha",
  script: "bg-node-script/15 text-node-script",
  newPage: "bg-node-newPage/15 text-node-newPage",
  switchPage: "bg-node-switchPage/15 text-node-switchPage",
  closePage: "bg-node-closePage/15 text-node-closePage",
};



/** 获取节点边框样式（带默认值） */
export function getNodeBorderStyle(nodeType: string): string {
  return colorMap[nodeType] || DEFAULT_BORDER;
}

/** 获取节点图标背景样式（带默认值） */
export function getNodeIconBgStyle(nodeType: string): string {
  return iconBgMap[nodeType] || DEFAULT_ICON_BG;
}


const DEFAULT_SIDE_BORDER = "border-node-default/40 hover:border-node-default hover:shadow-[0_0_12px_-3px_hsl(var(--node-default)/0.3)]";
const DEFAULT_SIDE_ICON_BG = "text-node-default";
export const sideColorMap: Record<string, string> = {
  navigate: "border-node-navigate/40 hover:border-node-navigate hover:shadow-[0_0_12px_-3px_hsl(var(--node-navigate)/0.3)]",
  foreach: "border-node-foreach/40 hover:border-node-foreach hover:shadow-[0_0_12px_-3px_hsl(var(--node-foreach)/0.3)]",
  while: "border-node-while/40 hover:border-node-while hover:shadow-[0_0_12px_-3px_hsl(var(--node-while)/0.3)]",
  for: "border-node-for/40 hover:border-node-for hover:shadow-[0_0_12px_-3px_hsl(var(--node-for)/0.3)]",
  click: "border-node-click/40 hover:border-node-click hover:shadow-[0_0_12px_-3px_hsl(var(--node-click)/0.3)]",
  check_existence: "border-node-check_existence/40 hover:border-node-check_existence hover:shadow-[0_0_12px_-3px_hsl(var(--node-check_existence)/0.3)]",
  type: "border-node-type/40 hover:border-node-type hover:shadow-[0_0_12px_-3px_hsl(var(--node-type)/0.3)]",
  wait: "border-node-wait/40 hover:border-node-wait hover:shadow-[0_0_12px_-3px_hsl(var(--node-wait)/0.3)]",
  screenshot: "border-node-screenshot/40 hover:border-node-screenshot hover:shadow-[0_0_12px_-3px_hsl(var(--node-screenshot)/0.3)]",
  scroll: "border-node-scroll/40 hover:border-node-scroll hover:shadow-[0_0_12px_-3px_hsl(var(--node-scroll)/0.3)]",
  locator: "border-node-locator/40 hover:border-node-locator hover:shadow-[0_0_12px_-3px_hsl(var(--node-locator)/0.3)]",
  count: "border-node-count/40 hover:border-node-count hover:shadow-[0_0_12px_-3px_hsl(var(--node-count)/0.3)]",
  all: "border-node-all/40 hover:border-node-all hover:shadow-[0_0_12px_-3px_hsl(var(--node-all)/0.3)]",
  first: "border-node-first/40 hover:border-node-first hover:shadow-[0_0_12px_-3px_hsl(var(--node-first)/0.3)]",
  last: "border-node-last/40 hover:border-node-last hover:shadow-[0_0_12px_-3px_hsl(var(--node-last)/0.3)]",
  nth: "border-node-nth/40 hover:border-node-nth hover:shadow-[0_0_12px_-3px_hsl(var(--node-nth)/0.3)]",
  map: "border-node-map/40 hover:border-node-map hover:shadow-[0_0_12px_-3px_hsl(var(--node-map)/0.3)]",
  textContent: "border-node-textContent/40 hover:border-node-textContent hover:shadow-[0_0_12px_-3px_hsl(var(--node-textContent)/0.3)]",
  innerText: "border-node-innerText/40 hover:border-node-innerText hover:shadow-[0_0_12px_-3px_hsl(var(--node-innerText)/0.3)]",
  inputValue: "border-node-inputValue/40 hover:border-node-inputValue hover:shadow-[0_0_12px_-3px_hsl(var(--node-inputValue)/0.3)]",
  getAttribute: "border-node-getAttribute/40 hover:border-node-getAttribute hover:shadow-[0_0_12px_-3px_hsl(var(--node-getAttribute)/0.3)]",
  isVisible: "border-node-isVisible/40 hover:border-node-isVisible hover:shadow-[0_0_12px_-3px_hsl(var(--node-isVisible)/0.3)]",
  isEnabled: "border-node-isEnabled/40 hover:border-node-isEnabled hover:shadow-[0_0_12px_-3px_hsl(var(--node-isEnabled)/0.3)]",
  isChecked: "border-node-isChecked/40 hover:border-node-isChecked hover:shadow-[0_0_12px_-3px_hsl(var(--node-isChecked)/0.3)]",
  hover: "border-node-hover/40 hover:border-node-hover hover:shadow-[0_0_12px_-3px_hsl(var(--node-hover)/0.3)]",
  check: "border-node-check/40 hover:border-node-check hover:shadow-[0_0_12px_-3px_hsl(var(--node-check)/0.3)]",
  uncheck: "border-node-uncheck/40 hover:border-node-uncheck hover:shadow-[0_0_12px_-3px_hsl(var(--node-uncheck)/0.3)]",
  cookie: "border-node-cookie/40 hover:border-node-cookie hover:shadow-[0_0_12px_-3px_hsl(var(--node-cookie)/0.3)]",
  localstorage: "border-node-localstorage/40 hover:border-node-localstorage hover:shadow-[0_0_12px_-3px_hsl(var(--node-localstorage)/0.3)]",
  if: "border-node-if/40 hover:border-node-if hover:shadow-[0_0_12px_-3px_hsl(var(--node-if)/0.3)]",
  extract: "border-node-extract/40 hover:border-node-extract hover:shadow-[0_0_12px_-3px_hsl(var(--node-extract)/0.3)]",
  break: "border-node-break/40 hover:border-node-break hover:shadow-[0_0_12px_-3px_hsl(var(--node-break)/0.3)]",
  continue: "border-node-continue/40 hover:border-node-continue hover:shadow-[0_0_12px_-3px_hsl(var(--node-continue)/0.3)]",
  stop: "border-node-stop/40 hover:border-node-stop hover:shadow-[0_0_12px_-3px_hsl(var(--node-stop)/0.3)]",
  set: "border-node-set/40 hover:border-node-set hover:shadow-[0_0_12px_-3px_hsl(var(--node-set)/0.3)]",
  document: "border-node-document/40 hover:border-node-document hover:shadow-[0_0_12px_-3px_hsl(var(--node-document)/0.3)]",
  title: "border-node-title/40 hover:border-node-title hover:shadow-[0_0_12px_-3px_hsl(var(--node-title)/0.3)]",
  url: "border-node-url/40 hover:border-node-url hover:shadow-[0_0_12px_-3px_hsl(var(--node-url)/0.3)]",
  content: "border-node-content/40 hover:border-node-content hover:shadow-[0_0_12px_-3px_hsl(var(--node-content)/0.3)]",
  viewport: "border-node-viewport/40 hover:border-node-viewport hover:shadow-[0_0_12px_-3px_hsl(var(--node-viewport)/0.3)]",
  press: "border-node-press/40 hover:border-node-press hover:shadow-[0_0_12px_-3px_hsl(var(--node-press)/0.3)]",
  selectOption: "border-node-selectOption/40 hover:border-node-selectOption hover:shadow-[0_0_12px_-3px_hsl(var(--node-selectOption)/0.3)]",
  waitFor: "border-node-waitFor/40 hover:border-node-waitFor hover:shadow-[0_0_12px_-3px_hsl(var(--node-waitFor)/0.3)]",
  waitForURL: "border-node-waitForURL/40 hover:border-node-waitForURL hover:shadow-[0_0_12px_-3px_hsl(var(--node-waitForURL)/0.3)]",
  waitForLoadState: "border-node-waitForLoadState/40 hover:border-node-waitForLoadState hover:shadow-[0_0_12px_-3px_hsl(var(--node-waitForLoadState)/0.3)]",
  httpRequest: "border-node-httpRequest/40 hover:border-node-httpRequest hover:shadow-[0_0_12px_-3px_hsl(var(--node-httpRequest)/0.3)]",
  file: "border-node-file/40 hover:border-node-file hover:shadow-[0_0_12px_-3px_hsl(var(--node-file)/0.3)]",
  mouse: "border-node-mouse/40 hover:border-node-mouse hover:shadow-[0_0_12px_-3px_hsl(var(--node-mouse)/0.3)]",
  ocrCaptcha: "border-node-ocrCaptcha/40 hover:border-node-ocrCaptcha hover:shadow-[0_0_12px_-3px_hsl(var(--node-ocrCaptcha)/0.3)]",
  sliderCaptcha: "border-node-sliderCaptcha/40 hover:border-node-sliderCaptcha hover:shadow-[0_0_12px_-3px_hsl(var(--node-sliderCaptcha)/0.3)]",
  script: "border-node-script/40 hover:border-node-script hover:shadow-[0_0_12px_-3px_hsl(var(--node-script)/0.3)]",
  newPage: "border-node-newPage/40 hover:border-node-newPage hover:shadow-[0_0_12px_-3px_hsl(var(--node-newPage)/0.3)]",
  switchPage: "border-node-switchPage/40 hover:border-node-switchPage hover:shadow-[0_0_12px_-3px_hsl(var(--node-switchPage)/0.3)]",
  closePage: "border-node-closePage/40 hover:border-node-closePage hover:shadow-[0_0_12px_-3px_hsl(var(--node-closePage)/0.3)]",
};

export const sideIconColorMap: Record<string, string> = {
  navigate: "text-node-navigate",
  foreach: "text-node-foreach",
  while: "text-node-while",
  for: "text-node-for",
  click: "text-node-click",
  check_existence: "text-node-check_existence",
  type: "text-node-type",
  wait: "text-node-wait",
  screenshot: "text-node-screenshot",
  scroll: "text-node-scroll",
  locator: "text-node-locator",
  count: "text-node-count",
  all: "text-node-all",
  first: "text-node-first",
  last: "text-node-last",
  nth: "text-node-nth",
  map: "text-node-map",
  textContent: "text-node-textContent",
  innerText: "text-node-innerText",
  inputValue: "text-node-inputValue",
  getAttribute: "text-node-getAttribute",
  isVisible: "text-node-isVisible",
  isEnabled: "text-node-isEnabled",
  isChecked: "text-node-isChecked",
  hover: "text-node-hover",
  check: "text-node-check",
  uncheck: "text-node-uncheck",
  cookie: "text-node-cookie",
  localstorage: "text-node-localstorage",
  if: "text-node-if",
  extract: "text-node-extract",
  break: "text-node-break",
  continue: "text-node-continue",
  stop: "text-node-stop",
  set: "text-node-set",
  document: "text-node-document",
  title: "text-node-title",
  url: "text-node-url",
  content: "text-node-content",
  viewport: "text-node-viewport",
  press: "text-node-press",
  selectOption: "text-node-selectOption",
  waitFor: "text-node-waitFor",
  waitForURL: "text-node-waitForURL",
  waitForLoadState: "text-node-waitForLoadState",
  httpRequest: "text-node-httpRequest",
  file: "text-node-file",
  mouse: "text-node-mouse",
  ocrCaptcha: "text-node-ocrCaptcha",
  sliderCaptcha: "text-node-sliderCaptcha",
  script: "text-node-script",
  newPage: "text-node-newPage",
  switchPage: "text-node-switchPage",
  closePage: "text-node-closePage",
};




/** 获取节点边框样式（带默认值） */
export function getSideNodeColorMap(nodeType: string): string {
  return sideColorMap[nodeType] || DEFAULT_SIDE_BORDER;
}

/** 获取节点图标背景样式（带默认值） */
export function getSideNodeIconColorMap(nodeType: string): string {
  return sideIconColorMap[nodeType] || DEFAULT_SIDE_ICON_BG;
}