import { ScanSearch } from "lucide-react";
import { type NodeTypeConfig } from "../nodeTypes";

const SliderCaptchaNode: NodeTypeConfig = {
  type: "sliderCaptcha",
  label: "Slider Captcha",
  icon: ScanSearch,
  color: "node-sliderCaptcha",
  description: "Solve image slider captcha by OCR matching and human-like drag",
  outputType: "object",
  inputDefs: [
    { key: "target", label: "Handle Target", description: "可选，引用滑块拖动把手 locator" },
  ],
  fields: [
    {
      key: "handleSelectorType",
      label: "Handle Locator Strategy",
      type: "select",
      options: [
        { label: "Playwright Native", value: "native" },
        { label: "CSS Selector", value: "css" },
        { label: "Text", value: "text" },
        { label: "Role", value: "role" },
        { label: "Test ID", value: "testid" },
        { label: "Label", value: "label" },
        { label: "Placeholder", value: "placeholder" },
        { label: "XPath", value: "xpath" },
      ],
      defaultValue: "native",
      valueSource: "params",
    },
    {
      key: "handleSelector",
      label: "Handle Selector",
      type: "text",
      placeholder: "div[class^='gocaptcha-module_dragBlock_']",
      defaultValue: "",
      valueSource: "params",
    },
    {
      key: "backgroundSelector",
      label: "Background Image Selector",
      type: "text",
      placeholder: "img[class^='gocaptcha-module_picture']",
      defaultValue: "",
      valueSource: "params",
    },
    {
      key: "sliderImageSelector",
      label: "Slider Piece Selector",
      type: "text",
      placeholder: "div[class^='index-module_tile'] img",
      defaultValue: "",
      valueSource: "params",
    },
    {
      key: "simple_target",
      label: "Simple Target",
      type: "checkbox",
      defaultValue: false,
      valueSource: "params",
    },
    {
      key: "successSelector",
      label: "Success Selector",
      type: "text",
      placeholder: "button:has-text('Verified')",
      defaultValue: "",
      valueSource: "params",
    },
    {
      key: "successText",
      label: "Success Text",
      type: "text",
      placeholder: "keep it up",
      defaultValue: "",
      valueSource: "params",
    },
    {
      key: "retryTriggerSelector",
      label: "Retry Trigger Selector",
      type: "text",
      placeholder: "span:has-text('Check In')",
      defaultValue: "",
      valueSource: "params",
    },
    {
      key: "refreshSelector",
      label: "Refresh Selector",
      type: "text",
      placeholder: ".captcha-refresh || svg[data-role='refresh']",
      defaultValue: "",
      valueSource: "params",
    },
    {
      key: "refreshTimeout",
      label: "Refresh Timeout (ms)",
      type: "number",
      defaultValue: 5000,
      valueSource: "params",
    },
    {
      key: "refreshWaitMs",
      label: "Wait After Refresh (ms)",
      type: "number",
      defaultValue: 1500,
      valueSource: "params",
    },
    {
      key: "offset",
      label: "Distance Offset",
      type: "number",
      defaultValue: -10,
      valueSource: "params",
    },
    {
      key: "minStep",
      label: "Min Step",
      type: "number",
      defaultValue: 5,
      valueSource: "params",
    },
    {
      key: "maxStep",
      label: "Max Step",
      type: "number",
      defaultValue: 12,
      valueSource: "params",
    },
    {
      key: "moveDelayMs",
      label: "Move Delay (ms)",
      type: "number",
      defaultValue: 20,
      valueSource: "params",
    },
    {
      key: "overshoot",
      label: "Overshoot",
      type: "number",
      defaultValue: 8,
      valueSource: "params",
    },
    {
      key: "backtrack",
      label: "Backtrack",
      type: "number",
      defaultValue: 2,
      valueSource: "params",
    },
    {
      key: "holdBeforeReleaseMs",
      label: "Hold Before Release (ms)",
      type: "number",
      defaultValue: 100,
      valueSource: "params",
    },
    {
      key: "waitAfterDragMs",
      label: "Wait After Drag (ms)",
      type: "number",
      defaultValue: 3000,
      valueSource: "params",
    },
    {
      key: "successTimeout",
      label: "Success Timeout (ms)",
      type: "number",
      defaultValue: 5000,
      valueSource: "params",
    },
    {
      key: "maxRetry",
      label: "Max Retry",
      type: "number",
      defaultValue: 3,
      valueSource: "params",
    },
  ],
  subtitle: "captcha × {maxRetry}",
};

export default SliderCaptchaNode;