from .common import (
    NodeHandler,
    build_locator,
    create_locator_descriptor,
    get_private_store,
    get_variable_store,
    normalize_node,
    resolve_locator_target,
    resolve_output_reference,
    resolve_output_reference_for_eval,
)
from .browser import (
    handle_document_node,
    handle_title_node,
    handle_url_node,
    handle_content_node,
    handle_viewport_node,
    handle_navigate_node,
    handle_locator_node,
    handle_count_node,
    handle_all_node,
    handle_first_node,
    handle_last_node,
    handle_nth_node,
    handle_click_node,
    handle_mouse_node,
    handle_fill_node,
    handle_type_node,
    handle_press_node,
    handle_hover_node,
    handle_ocr_captcha_node,
    handle_slider_captcha_node,
    handle_check_node,
    handle_uncheck_node,
    handle_select_option_node,
    handle_scroll_node,
    handle_text_content_node,
    handle_inner_text_node,
    handle_input_value_node,
    handle_get_attribute_node,
    handle_is_visible_node,
    handle_is_enabled_node,
    handle_is_checked_node,
    handle_screenshot_node,
    handle_wait_node,
    handle_wait_for_node,
    handle_wait_for_url_node,
    handle_wait_for_load_state_node,
    handle_script_node,
    handle_new_page_node,
    handle_switch_page_node,
    handle_close_page_node,
    handle_current_page_node,
    handle_check_existence_node,
)
from .storage import handle_cookie_node, handle_localstorage_node
from .filesystem import handle_file_node
from .network import handle_http_request_node
from .transform import handle_transform_node
from .expression import handle_expression_node
from .faker_node import handle_faker_node
from .flow_control import (
    evaluate_condition_config,
    handle_break_node,
    handle_continue_node,
    handle_extract_node,
    handle_for_node,
    handle_foreach_node,
    handle_if_node,
    handle_map_node,
    handle_random_node,
    handle_stop_node,
    handle_set_variable_node,
    handle_wait_for_user_node,
    handle_while_node,
)

NODE_HANDLERS = {
    "document": handle_document_node,
    "title": handle_title_node,
    "url": handle_url_node,
    "content": handle_content_node,
    "viewport": handle_viewport_node,
    "navigate": handle_navigate_node,
    "locator": handle_locator_node,
    "count": handle_count_node,
    "all": handle_all_node,
    "first": handle_first_node,
    "last": handle_last_node,
    "nth": handle_nth_node,
    "cookie": handle_cookie_node,
    "localstorage": handle_localstorage_node,
    "file": handle_file_node,
    "httpRequest": handle_http_request_node,
    "transform": handle_transform_node,
    "expression": handle_expression_node,
    "faker": handle_faker_node,
    "click": handle_click_node,
    "mouse": handle_mouse_node,
    "type": handle_type_node,
    "fill": handle_fill_node,
    "press": handle_press_node,
    "hover": handle_hover_node,
    "ocrCaptcha": handle_ocr_captcha_node,
    "sliderCaptcha": handle_slider_captcha_node,
    "check": handle_check_node,
    "uncheck": handle_uncheck_node,
    "selectOption": handle_select_option_node,
    "scroll": handle_scroll_node,
    "textContent": handle_text_content_node,
    "innerText": handle_inner_text_node,
    "inputValue": handle_input_value_node,
    "getAttribute": handle_get_attribute_node,
    "isVisible": handle_is_visible_node,
    "isEnabled": handle_is_enabled_node,
    "isChecked": handle_is_checked_node,
    "screenshot": handle_screenshot_node,
    "wait": handle_wait_node,
    "waitFor": handle_wait_for_node,
    "waitForURL": handle_wait_for_url_node,
    "waitForLoadState": handle_wait_for_load_state_node,
    "script": handle_script_node,
    "newPage": handle_new_page_node,
    "switchPage": handle_switch_page_node,
    "closePage": handle_close_page_node,
    "currentPage": handle_current_page_node,
    "extract": handle_extract_node,
    "foreach": handle_foreach_node,
    "while": handle_while_node,
    "for": handle_for_node,
    "map": handle_map_node,
    "check_existence": handle_check_existence_node,
    "if": handle_if_node,
    "break": handle_break_node,
    "continue": handle_continue_node,
    "stop": handle_stop_node,
    "set": handle_set_variable_node,
    "random": handle_random_node,
    "waitForUser": handle_wait_for_user_node,
}

__all__ = [
    "NodeHandler",
    "NODE_HANDLERS",
    "build_locator",
    "create_locator_descriptor",
    "get_private_store",
    "get_variable_store",
    "normalize_node",
    "resolve_locator_target",
    "resolve_output_reference",
    "resolve_output_reference_for_eval",
    "evaluate_condition_config",
]
